name: Deploy frontend to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  upload-pages-artifact:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node (optional)
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Prepare pages content
        run: |
          # Ensure frontend folder exists
          if [ ! -d frontend ]; then
            echo "frontend folder not found"; exit 1;
          fi
          # (Optional) run build steps here if you add a toolchain later
          echo "Using contents of ./frontend as Pages root"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: frontend

  deploy-pages:
    needs: upload-pages-artifact
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
